version: "3.9"

services:
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: chatbot
    restart: unless-stopped
    volumes:
      - ./chatbot:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.next/cache
    ports:
      - "3031:3031"
    environment:
      NODE_ENV: development
    tty: true
    networks:
      local_bridge:
        ipv4_address: 172.20.2.2


  myaichat:
    build:
      context: ./myaichat
      dockerfile: Dockerfile
    container_name: myaichat
    restart: unless-stopped
    volumes:
      - ./myaichat:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.next/cache
    ports:
      - "3032:3032"
    environment:
      NODE_ENV: development
    tty: true
    networks:
      local_bridge:
        ipv4_address: 172.20.2.3

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    restart: unless-stopped
    volumes:
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.next/cache
    ports:
      - "3033:3033"
    environment:
      NODE_ENV: development
    tty: true
    networks:
      local_bridge:
        ipv4_address: 172.20.2.4

networks:
  local_bridge:
    name: docker_network
    driver: bridge
    attachable: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.2.0/24
          gateway: 172.20.0.1