version: "3.9"

services:
  webserver:
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./myaichat:/var/www/myaichat
      - ./chatbot:/var/www/chatbot
      - ./chatbot_loader:/var/www/chatbot_loader
    networks:
      local_bridge:
        ipv4_address: 172.20.2.0

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - webserver
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/vendor
      - /app/node_modules
      - /app/public
      - /app/storage
      - /app/bootstrap/cache
    ports:
      - "8000:8000"
      #- "8000:80"
    environment:
      APP_ENV: production
    tty: true
    networks:
      local_bridge:
        ipv4_address: 172.20.2.3

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: chatbot
    command: yarn dev
    depends_on:
      - webserver
    restart: unless-stopped
    volumes:
      - ./chatbot:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.next/cache
    ports:
      - "3031:3031"
    environment:
      NODE_ENV: production
    tty: true
    networks:
      local_bridge:
        ipv4_address: 172.20.2.5

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    command: yarn dev
    depends_on:
      - webserver
    restart: unless-stopped
    volumes:
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.next/cache
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: production
    tty: true
    networks:
      local_bridge:
        ipv4_address: 172.20.2.4

networks:
  local_bridge:
    name: docker_network
    driver: bridge
    attachable: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.2.0/24
          gateway: 172.20.0.1