name: Pre-Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_to_preprod:
    name: Deploy to Pre-Production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway Pre-Production
      run: |
        # Set the RAILWAY_TOKEN environment variable
        export RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN_PREPROD }}
        # Run the deployment command for your services in pre-production
        railway up -e preproduction -s myaichat
        railway up -e preproduction -s support.myaichat
        railway up -e preproduction -s admin.myaichat
        railway up -e preproduction -s loader.myaichat
        railway up -e preproduction -s api.myaichat
        railway up -e preproduction -s dashboard.myaichat
        railway up -e preproduction -s chatbot.myaichat
