name: Production Deployment

on:
  workflow_run:
    workflows: ["Pre-Production Deployment"]
    types:
      - completed

jobs:
  deploy_to_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'workflow_run' && needs.deploy_to_preprod.result == 'success'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Simulate Comment for Production Approval
      run: |
        echo "To approve the production deployment, run the following command in your terminal:"
        echo "gh pr comment ${{ github.event.workflow_run.pull_requests[0].number }} --body '/approve'"
