name: Production Deployment

on:
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  deploy_to_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'workflow_run' && needs.preprod.result == 'success'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway Pre-Production
      run: |
        # Set the RAILWAY_TOKEN environment variable
        export RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN_PROD }}
        # Run the deployment command for your services in production
        railway up -e preproduction -s myaichat
        railway up -e preproduction -s loader.myaichat
        railway up -e preproduction -s api.myaichat
        railway up -e preproduction -s dashboard.myaichat
        railway up -e preproduction -s chatbot.myaichat
