name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'

jobs:
  deploy_to_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway Production
        run: |
          # Set the RAILWAY_TOKEN environment variable
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN_PROD }}
          # Run the deployment command for your services in production
          railway up -e production -s myaichat
          railway up -e production -s loader.myaichat
          railway up -e production -s api.myaichat
          railway up -e production -s dashboard.myaichat
          railway up -e production -s chatbot.myaichat
