name: Railway Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_to_preprod:
    name: Deploy to Pre-Production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway Pre-Production
      run: |
        # Set the RAILWAY_TOKEN environment variable
        export RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN_PREPROD }}

        # Run the deployment command for a specific service
        railway up -e preproduction -s myaichat
        railway up -e preproduction -s loader.myaichat
        railway up -e preproduction -s api.myaichat
        railway up -e preproduction -s dashboard.myaichat
        railway up -e preproduction -s chatbot.myaichat

  deploy_to_prod:
    name: Deploy to Production
    needs: deploy_to_preprod
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Check Pre-Production Deployment Status
      run: |
        deployment_status=$(railway status preproduction)
        echo "Pre-Production Deployment Status: $deployment_status"

        if [[ $deployment_status == "good" ]]; then
          # Set the RAILWAY_TOKEN environment variable
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN_PROD }}

          # Run the production deployment command for a specific service
          railway up -e production -s myaichat
          railway up -e production -s loader.myaichat
          railway up -e production -s api.myaichat
          railway up -e production -s dashboard.myaichat
          railway up -e production -s chatbot.myaichat
        else
          echo "Pre-Production deployment is not in a good state. Skipping Production deployment."
        fi
